---
# - name: Gather os specific variables
#   ansible.builtin.include_vars: "{{ item }}"
#   with_first_found:
#     - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
#     - "{{ ansible_distribution }}.yml"
#   ignore_errors: true  # noqa ignore-errors

- name: Gather os specific tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  ignore_errors: true  # noqa ignore-errors
