---
- name: Set Zabbix repo URL - base part for 6.0 - 7.0
  ansible.builtin.set_fact:
    repo_url_base: "https://repo.zabbix.com/zabbix/{{ zabbix_agent2_version }}"
  when: zabbix_agent2_version is version('7.2', '<')

- name: Set Zabbix repo URL - base part for 7.2 and newer
  ansible.builtin.set_fact:
    repo_url_base: "https://repo.zabbix.com/zabbix/{{ zabbix_agent2_version }}/release"
  when: zabbix_agent2_version is version('7.2', '>=')

- name: Set Zabbix repo URL - path part
  ansible.builtin.set_fact:
    repo_url_path: "/debian/pool/main/z/zabbix-release/zabbix-release_latest_"

- name: Set Zabbix repo URL - filename part
  ansible.builtin.set_fact:
    repo_url_filename: "{{ zabbix_agent2_version }}+debian{{ ansible_distribution_major_version }}_all.deb"

- name: Set Zabbix repo URL - complete
  ansible.builtin.set_fact:
    repo_url: "{{ repo_url_base }}{{ repo_url_path }}{{ repo_url_filename }}"

- name: Debug repo URL
  ansible.builtin.debug:
    var: repo_url

- name: Install Zabbix repo .deb
  ansible.builtin.apt:
    deb: "{{ repo_url }}"

...
